import type { Experience, Skill } from '@/domain/entities/Experience';
import type { ExperienceRepository } from '@/domain/repositories/ExperienceRepository';

/**
 * Static implementation of ExperienceRepository for demo purposes
 */
export class StaticExperienceRepository implements ExperienceRepository {
  private getExperiences(t: (key: string) => string): Experience[] {
    return [
      {
        id: '1',
        company: t('experience.experiences.sofkaTechnologies.company'),
        position: t('experience.experiences.sofkaTechnologies.position'),
        description: t('experience.experiences.sofkaTechnologies.description'),
        achievements: [
          t('experience.experiences.sofkaTechnologies.achievements.0'),
          t('experience.experiences.sofkaTechnologies.achievements.1'),
          t('experience.experiences.sofkaTechnologies.achievements.2'),
          t('experience.experiences.sofkaTechnologies.achievements.3'),
        ],
        technologies: [
          'Java',
          'Spring Boot',
          'Angular',
          'TypeScript',
          'Clean Architecture',
          'Microservices',
        ],
        startDate: new Date('2024-11-05'),
        endDate: undefined,
        location: t('experience.experiences.sofkaTechnologies.location'),
        companyUrl: 'https://sofka.com.co',
      },
      {
        id: '2',
        company: t('experience.experiences.teamInternational.company'),
        position: t('experience.experiences.teamInternational.position'),
        description: t('experience.experiences.teamInternational.description'),
        achievements: [
          t('experience.experiences.teamInternational.achievements.0'),
          t('experience.experiences.teamInternational.achievements.1'),
          t('experience.experiences.teamInternational.achievements.2'),
          t('experience.experiences.teamInternational.achievements.3'),
        ],
        technologies: [
          'Java',
          'Spring Boot',
          'TypeScript',
          'Angular',
          'Python',
          'MySQL',
          'DB2',
          'DynamoDB',
          'AWS Lambda',
          'AWS ECS',
          'AWS S3',
          'API Gateway',
          'CloudFormation',
          'Terraform',
          'AWS Glue',
          'Kinesis',
          'SQS',
          'SNS',
          'CloudWatch',
          'EC2',
          'RDS',
          'DocumentDB',
        ],
        startDate: new Date('2023-05-02'),
        endDate: new Date('2024-11-15'),
        location: t('experience.experiences.teamInternational.location'),
        companyUrl: 'https://www.teaminternational.com',
      },
      {
        id: '3',
        company: t('experience.experiences.ceibaSoftwareHouse.company'),
        position: t('experience.experiences.ceibaSoftwareHouse.position'),
        description: t('experience.experiences.ceibaSoftwareHouse.description'),
        achievements: [
          t('experience.experiences.ceibaSoftwareHouse.achievements.0'),
          t('experience.experiences.ceibaSoftwareHouse.achievements.1'),
          t('experience.experiences.ceibaSoftwareHouse.achievements.2'),
          t('experience.experiences.ceibaSoftwareHouse.achievements.3'),
        ],
        technologies: [
          'Java',
          'Spring Boot',
          'Reactive Commons',
          'RabbitMQ',
          'TypeScript',
          'Angular',
          'Azure DevOps',
          'Microservices',
          'Event-Driven Architecture',
        ],
        startDate: new Date('2022-05-01'),
        endDate: new Date('2023-05-02'),
        location: t('experience.experiences.ceibaSoftwareHouse.location'),
        companyUrl: 'https://www.ceiba.com.co',
      },
      {
        id: '4',
        company: t('experience.experiences.nevuSAS.company'),
        position: t('experience.experiences.nevuSAS.position'),
        description: t('experience.experiences.nevuSAS.description'),
        achievements: [
          t('experience.experiences.nevuSAS.achievements.0'),
          t('experience.experiences.nevuSAS.achievements.1'),
          t('experience.experiences.nevuSAS.achievements.2'),
          t('experience.experiences.nevuSAS.achievements.3'),
        ],
        technologies: [
          'Java',
          'Spring Boot',
          'Python',
          'Django',
          'Node.js',
          'TypeScript',
          'React',
          'JavaScript',
          'MySQL',
          'MongoDB',
          'Docker',
          'Jenkins',
          'SonarQube',
          'AWS S3',
          'AWS Lambda',
          'AWS ECS',
          'AWS Cognito',
          'AWS RDS',
          'EC2',
          'Polygon',
          'Blockchain',
          'CI/CD',
        ],
        startDate: new Date('2021-05-01'),
        endDate: new Date('2023-05-02'),
        location: t('experience.experiences.nevuSAS.location'),
        companyUrl: 'https://www.nevu.services',
      },
      {
        id: '5',
        company: t('experience.experiences.freelance.company'),
        position: t('experience.experiences.freelance.position'),
        description: t('experience.experiences.freelance.description'),
        achievements: [
          t('experience.experiences.freelance.achievements.0'),
          t('experience.experiences.freelance.achievements.1'),
          t('experience.experiences.freelance.achievements.2'),
          t('experience.experiences.freelance.achievements.3'),
        ],
        technologies: [
          'Java',
          'Spring Boot',
          'Spring Cloud',
          'Mockito',
          'JUnit',
          'JavaScript',
          'Vue.js',
          'React Native',
          'Microservices',
          'Integration Testing',
        ],
        startDate: new Date('2021-01-16'),
        endDate: new Date('2021-05-01'),
        location: t('experience.experiences.freelance.location'),
        companyUrl: 'https://icesi.edu.co',
      },
    ];
  }

  private readonly skills: Skill[] = [
    // Frontend
    { id: '1', name: 'Angular', category: 'frontend', level: 'expert', yearsOfExperience: 5 },
    { id: '2', name: 'TypeScript', category: 'frontend', level: 'expert', yearsOfExperience: 5 },
    { id: '3', name: 'React', category: 'frontend', level: 'advanced', yearsOfExperience: 4 },
    { id: '4', name: 'Vue.js', category: 'frontend', level: 'advanced', yearsOfExperience: 3 },
    { id: '5', name: 'JavaScript', category: 'frontend', level: 'expert', yearsOfExperience: 6 },
    { id: '6', name: 'HTML5', category: 'frontend', level: 'expert', yearsOfExperience: 6 },
    { id: '7', name: 'CSS3', category: 'frontend', level: 'expert', yearsOfExperience: 6 },
    {
      id: '8',
      name: 'Tailwind CSS',
      category: 'frontend',
      level: 'advanced',
      yearsOfExperience: 2,
    },
    {
      id: '9',
      name: 'React Native',
      category: 'frontend',
      level: 'intermediate',
      yearsOfExperience: 2,
    },

    // Backend
    { id: '10', name: 'Java', category: 'backend', level: 'expert', yearsOfExperience: 6 },
    { id: '11', name: 'Spring Boot', category: 'backend', level: 'expert', yearsOfExperience: 6 },
    {
      id: '12',
      name: 'Spring Cloud',
      category: 'backend',
      level: 'advanced',
      yearsOfExperience: 3,
    },
    { id: '13', name: 'Node.js', category: 'backend', level: 'advanced', yearsOfExperience: 4 },
    { id: '14', name: 'Python', category: 'backend', level: 'advanced', yearsOfExperience: 4 },
    { id: '15', name: 'Django', category: 'backend', level: 'intermediate', yearsOfExperience: 2 },
    { id: '16', name: 'REST APIs', category: 'backend', level: 'expert', yearsOfExperience: 6 },
    { id: '17', name: 'Microservices', category: 'backend', level: 'expert', yearsOfExperience: 5 },
    {
      id: '18',
      name: 'Event-Driven Architecture',
      category: 'backend',
      level: 'advanced',
      yearsOfExperience: 3,
    },
    {
      id: '19',
      name: 'Reactive Programming',
      category: 'backend',
      level: 'advanced',
      yearsOfExperience: 3,
    },

    // Database
    { id: '20', name: 'MySQL', category: 'database', level: 'expert', yearsOfExperience: 5 },
    { id: '21', name: 'MongoDB', category: 'database', level: 'advanced', yearsOfExperience: 4 },
    { id: '22', name: 'DynamoDB', category: 'database', level: 'advanced', yearsOfExperience: 3 },
    { id: '23', name: 'PostgreSQL', category: 'database', level: 'advanced', yearsOfExperience: 3 },
    { id: '24', name: 'DB2', category: 'database', level: 'intermediate', yearsOfExperience: 2 },
    {
      id: '25',
      name: 'DocumentDB',
      category: 'database',
      level: 'intermediate',
      yearsOfExperience: 2,
    },

    // DevOps & Cloud
    { id: '26', name: 'AWS', category: 'devops', level: 'expert', yearsOfExperience: 5 },
    { id: '27', name: 'Docker', category: 'devops', level: 'expert', yearsOfExperience: 4 },
    { id: '28', name: 'Terraform', category: 'devops', level: 'advanced', yearsOfExperience: 3 },
    {
      id: '29',
      name: 'CloudFormation',
      category: 'devops',
      level: 'advanced',
      yearsOfExperience: 3,
    },
    { id: '30', name: 'Jenkins', category: 'devops', level: 'advanced', yearsOfExperience: 3 },
    { id: '31', name: 'CI/CD', category: 'devops', level: 'expert', yearsOfExperience: 4 },
    { id: '32', name: 'Azure DevOps', category: 'devops', level: 'advanced', yearsOfExperience: 2 },
    {
      id: '33',
      name: 'Kubernetes',
      category: 'devops',
      level: 'intermediate',
      yearsOfExperience: 2,
    },

    // Messaging & Integration
    { id: '34', name: 'RabbitMQ', category: 'tools', level: 'advanced', yearsOfExperience: 3 },
    { id: '35', name: 'Kafka', category: 'tools', level: 'intermediate', yearsOfExperience: 2 },
    { id: '36', name: 'AWS SQS', category: 'tools', level: 'advanced', yearsOfExperience: 3 },
    { id: '37', name: 'AWS SNS', category: 'tools', level: 'advanced', yearsOfExperience: 3 },

    // Testing
    { id: '38', name: 'JUnit', category: 'tools', level: 'expert', yearsOfExperience: 5 },
    { id: '39', name: 'Mockito', category: 'tools', level: 'expert', yearsOfExperience: 5 },
    {
      id: '40',
      name: 'Integration Testing',
      category: 'tools',
      level: 'advanced',
      yearsOfExperience: 4,
    },
    { id: '41', name: 'SonarQube', category: 'tools', level: 'advanced', yearsOfExperience: 3 },

    // Tools
    { id: '42', name: 'Git', category: 'tools', level: 'expert', yearsOfExperience: 6 },
    {
      id: '43',
      name: 'Blockchain',
      category: 'tools',
      level: 'intermediate',
      yearsOfExperience: 2,
    },
    {
      id: '44',
      name: 'Clean Architecture',
      category: 'tools',
      level: 'expert',
      yearsOfExperience: 4,
    },
  ];

  async getAllExperiences(t?: (key: string) => string): Promise<Experience[]> {
    if (!t) {
      return [
        {
          id: '1',
          company: 'Sofka Technologies',
          position: 'Development Consultant',
          description:
            'Led software development and adaptation projects using Java, Spring Boot, and Angular with clean architecture principles',
          achievements: [
            'Designed and implemented custom IT solutions serving enterprise-level clients',
            'Identified and proposed process optimizations improving development efficiency by 30%',
            'Coordinated cross-functional teams ensuring solutions met quality standards and business requirements',
            'Applied clean architecture patterns to maintain scalable and maintainable codebases',
          ],
          technologies: [
            'Java',
            'Spring Boot',
            'Angular',
            'TypeScript',
            'Clean Architecture',
            'Microservices',
          ],
          startDate: new Date('2024-11-05'),
          endDate: undefined,
          location: 'Remote',
          companyUrl: 'https://sofka.com.co',
        },
        {
          id: '2',
          company: 'Team International',
          position: 'Full Stack Engineer',
          description:
            'Developed full-stack applications with Java/Spring Boot backend and TypeScript/Angular frontend, implementing AWS cloud infrastructure',
          achievements: [
            'Architected and deployed AWS solutions using 15+ services including Lambda, ECS, DynamoDB, and API Gateway',
            'Implemented Infrastructure as Code using CloudFormation and Terraform for automated deployments',
            'Developed data processing pipelines using Python, AWS Glue, and Kinesis',
            'Managed multi-database architecture with MySQL, DB2, and DynamoDB for optimal performance',
            'Built scalable microservices architecture handling high-volume transactions',
          ],
          technologies: [
            'Java',
            'Spring Boot',
            'TypeScript',
            'Angular',
            'Python',
            'MySQL',
            'DB2',
            'DynamoDB',
            'AWS Lambda',
            'AWS ECS',
            'AWS S3',
            'API Gateway',
            'CloudFormation',
            'Terraform',
            'AWS Glue',
            'Kinesis',
            'SQS',
            'SNS',
            'CloudWatch',
            'EC2',
            'RDS',
            'DocumentDB',
          ],
          startDate: new Date('2023-05-02'),
          endDate: new Date('2024-11-15'),
          location: 'Remote',
          companyUrl: 'https://www.teaminternational.com',
        },
        {
          id: '3',
          company: 'Ceiba Software House',
          position: 'Developer Architect',
          description:
            'Architected and developed reactive microservices using Spring Boot with Reactive Commons and Angular frontend',
          achievements: [
            'Designed event-driven microservices architecture using RabbitMQ for inter-service communication',
            'Implemented reactive programming patterns improving application responsiveness by 40%',
            'Managed CI/CD pipelines and deployment automation using Azure DevOps',
            'Led incident response and resolution for production applications ensuring 99.9% uptime',
            'Established monitoring and alerting systems for proactive issue detection',
          ],
          technologies: [
            'Java',
            'Spring Boot',
            'Reactive Commons',
            'RabbitMQ',
            'TypeScript',
            'Angular',
            'Azure DevOps',
            'Microservices',
            'Event-Driven Architecture',
          ],
          startDate: new Date('2022-05-01'),
          endDate: new Date('2023-05-02'),
          location: 'Remote',
          companyUrl: 'https://www.ceiba.com.co',
        },
        {
          id: '4',
          company: 'Nevu S.A.S',
          position: 'Co-Founder & Full Stack Engineer',
          description:
            'Co-founded fintech startup integrating blockchain technology with traditional financial services',
          achievements: [
            'Built complete cloud infrastructure on AWS managing 10+ services for production environment',
            'Integrated Polygon blockchain technology for secure financial transactions',
            'Developed automated CI/CD pipelines using Docker, Jenkins, and SonarQube reducing deployment time by 70%',
            'Created full-stack applications using Java/Spring Boot, Python/Django, Node.js, and React.js',
            'Managed MySQL and MongoDB databases ensuring data integrity and optimal performance',
            'Implemented AWS Cognito authentication system securing user access and data',
          ],
          technologies: [
            'Java',
            'Spring Boot',
            'Python',
            'Django',
            'Node.js',
            'TypeScript',
            'React',
            'JavaScript',
            'MySQL',
            'MongoDB',
            'Docker',
            'Jenkins',
            'SonarQube',
            'AWS S3',
            'AWS Lambda',
            'AWS ECS',
            'AWS Cognito',
            'AWS RDS',
            'EC2',
            'Polygon',
            'Blockchain',
            'CI/CD',
          ],
          startDate: new Date('2021-05-01'),
          endDate: new Date('2023-05-02'),
          location: 'Cali, Colombia',
          companyUrl: 'https://www.nevu.services',
        },
        {
          id: '5',
          company: 'Freelance',
          position: 'Backend Developer',
          description:
            'Provided backend development services for multiple clients building microservices and full-stack applications',
          achievements: [
            'Developed Spring Cloud microservices architecture for distributed systems',
            'Implemented comprehensive testing strategy using Mockito, JUnit, and integration tests achieving 85% code coverage',
            'Built responsive web applications using Vue.js frontend framework',
            'Created cross-platform mobile applications using React Native',
            'Delivered projects on time and within budget for diverse client requirements',
          ],
          technologies: [
            'Java',
            'Spring Boot',
            'Spring Cloud',
            'Mockito',
            'JUnit',
            'JavaScript',
            'Vue.js',
            'React Native',
            'Microservices',
            'Integration Testing',
          ],
          startDate: new Date('2021-01-16'),
          endDate: new Date('2021-05-01'),
          location: 'Cali, Colombia',
          companyUrl: 'https://icesi.edu.co',
        },
      ];
    }

    return this.getExperiences(t);
  }

  async getAllSkills(): Promise<Skill[]> {
    return [...this.skills];
  }

  async getSkillsByCategory(category: string): Promise<Skill[]> {
    return this.skills.filter((skill) => skill.category === category);
  }
}
